server:
  port: 9095

spring:
  datasource:
    url: jdbc:mysql://172.16.14.9:3306/intellisense?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 3000ms

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
redis:
  database: intellisense
  key:
    admin: 'intellisense:user'
  expire:
    common: 86400

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000